version: "3.9"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    image: sales-crm-image:latest
    ports:
      - "5005:5005"
    env_file:
      - ./app/.env
    depends_on:
      - redis
      - db

  celery:
    image: sales-crm-image:latest
    command: /app/.venv/bin/celery -A app.celery_worker.celery worker --loglevel=info
    env_file:
      - ./app/.env
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: basit456
      MYSQL_DATABASE: messenger_crm
    ports:
      - "3306:3306"