version: "3.9"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    image: basit456/sales-crm-image:latest
    ports:
      - "5005:5005"
    env_file:
      - ./app/.env
    depends_on:
      - redis


  celery:
    image: basit456/sales-crm-image:latest
    command: /app/.venv/bin/celery -A app.celery_worker.celery worker --loglevel=info
    env_file:
      - ./app/.env
    environment:
      - IS_CELERY_WORKER=true  # ✅ So we can skip migrations inside app init
    depends_on:
      - redis
 

  ai-agent:
    build:
      context: ../ai-agent
      dockerfile: Dockerfile-ai-agent  # ✅ Specify the custom Dockerfile name
    image: basit456/ai-agent:latest
    ports:
      - "8000:8000"
    env_file:
      - ../ai-agent/.env
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  ngix:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
      - ai-agent

