name: Build & Deploy Sales CRM

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image with cache
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile-flask
        platforms: linux/amd64,linux/arm64
        push: true
        tags: basit456/sales-crm-image:latest
        cache-from: type=registry,ref=basit456/sales-crm-image:buildcache
        cache-to: type=registry,ref=basit456/sales-crm-image:buildcache,mode=max

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/Sales_crm
          git pull
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> app/.env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> app/.env
          docker compose down
          docker compose pull
          docker compose up -d